#pragma once

const int32_t BUTTON_U = SDL_SCANCODE_W;
const int32_t BUTTON_HARD_DROP = SDL_SCANCODE_U;
const int32_t BUTTON_L = SDL_SCANCODE_A;
const int32_t BUTTON_D = SDL_SCANCODE_S;
const int32_t BUTTON_R = SDL_SCANCODE_D;
const int32_t BUTTON_A = SDL_SCANCODE_J;
const int32_t BUTTON_B = SDL_SCANCODE_K;
const int32_t BUTTON_C = SDL_SCANCODE_L;
const int32_t BUTTON_RESET = SDL_SCANCODE_R;
const int32_t BUTTON_QUIT = SDL_SCANCODE_ESCAPE;
const int32_t BUTTON_SCALE_UP = SDL_SCANCODE_EQUALS;
const int32_t BUTTON_SCALE_DOWN = SDL_SCANCODE_MINUS;
const int32_t BUTTON_MUTE = SDL_SCANCODE_P;
const int32_t BUTTON_MYSTERY = SDL_SCANCODE_KP_MINUS;