#pragma once

const int32_t BUTTON_U = SDL_SCANCODE_W;
const int32_t BUTTON_HARD_DROP = SDL_SCANCODE_U;
const int32_t BUTTON_L = SDL_SCANCODE_A;
const int32_t BUTTON_D = SDL_SCANCODE_S;
const int32_t BUTTON_R = SDL_SCANCODE_D;
const int32_t BUTTON_A = SDL_SCANCODE_J;
const int32_t BUTTON_B = SDL_SCANCODE_K;
const int32_t BUTTON_C = SDL_SCANCODE_L;
const int32_t BUTTON_RESET = SDL_SCANCODE_R;
const int32_t BUTTON_START = SDL_SCANCODE_RETURN;
const int32_t BUTTON_QUIT = SDL_SCANCODE_ESCAPE;
const int32_t BUTTON_SCALE_UP = SDL_SCANCODE_EQUALS;
const int32_t BUTTON_SCALE_DOWN = SDL_SCANCODE_MINUS;
const int32_t BUTTON_TOGGLE_ROTATION_SYSTEM = SDL_SCANCODE_0;
const int32_t BUTTON_MUTE = SDL_SCANCODE_P;
const int32_t BUTTON_MYSTERY = SDL_SCANCODE_KP_MINUS;

const int32_t GAMEPAD_U = SDL_GAMEPAD_BUTTON_DPAD_UP;
const int32_t GAMEPAD_D = SDL_GAMEPAD_BUTTON_DPAD_DOWN;
const int32_t GAMEPAD_L = SDL_GAMEPAD_BUTTON_DPAD_LEFT;
const int32_t GAMEPAD_R = SDL_GAMEPAD_BUTTON_DPAD_RIGHT;
const int32_t GAMEPAD_HARD_DROP = SDL_GAMEPAD_BUTTON_LEFT_SHOULDER;
const int32_t GAMEPAD_A = SDL_GAMEPAD_BUTTON_WEST;
const int32_t GAMEPAD_B = SDL_GAMEPAD_BUTTON_EAST;
const int32_t GAMEPAD_C = SDL_GAMEPAD_BUTTON_SOUTH;
const int32_t GAMEPAD_RESET = SDL_GAMEPAD_BUTTON_BACK;
const int32_t GAMEPAD_START = SDL_GAMEPAD_BUTTON_START;